DROP TABLE IF EXISTS user_role;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;

CREATE TABLE users
(
    id INT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE roles
(
    id INT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_role
(
    user_id INT REFERENCES users(id) NOT NULL,
    role_id INT REFERENCES roles(id) NOT NULL
);

INSERT INTO roles VALUES (1, 'Admin');
INSERT INTO roles VALUES (2, 'User');

INSERT INTO users VALUES (1, 'User1');
INSERT INTO users VALUES (2, 'User2');
INSERT INTO users VALUES (3, 'User3');

INSERT INTO user_role VALUES (1, 1);
INSERT INTO user_role VALUES (1, 2);
INSERT INTO user_role VALUES (2, 1);
INSERT INTO user_role VALUES (3, 2);
